AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Roastly API - AWS SAM Version

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 30
    MemorySize: 128
    Environment:
      Variables:
        PRODUCTS_TABLE: !Ref ProductsTable

Resources:

  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: roastly-dev-models
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  CreateProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/controllers/products.createHandler
      Events:
        CreateProductApi:
          Type: HttpApi
          Properties:
            Path: /products
            Method: POST

  GetProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/controllers/products.getHandler
      Events:
        GetProductApi:
          Type: HttpApi
          Properties:
            Path: /products/{id}
            Method: GET

  ListProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/controllers/products.listHandler
      Events:
        ListProductsApi:
          Type: HttpApi
          Properties:
            Path: /products
            Method: GET

  UpdateProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/controllers/products.updateHandler
      Events:
        UpdateProductApi:
          Type: HttpApi
          Properties:
            Path: /products/{id}
            Method: PUT

  DeleteProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/controllers/products.deleteHandler
      Events:
        DeleteProductApi:
          Type: HttpApi
          Properties:
            Path: /products/{id}
            Method: DELETE